CREATE TABLE characters (
    id bigint PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    species VARCHAR(100) NOT NULL,
    type VARCHAR(100) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    origin VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    image text[] NOT NULL,
    episode TEXT[]
);

ALTER TABLE characters
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE characters ALTER COLUMN image TYPE text USING image[1];

drop table characters;



